baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sheldon Reay'
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
googleAnalytics = 'G-9XF6D6EMVY'